#include "cad_sampling.h"

#include <algorithm>
#include <cerrno>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#if defined(_WIN32)
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#endif

namespace {

struct PlyPoint {
    float x;
    float y;
    float z;
    float nx;
    float ny;
    float nz;
    uint32_t face_id;
};
static_assert(sizeof(PlyPoint) == 28, "unexpected PLY point padding");

uint64_t ParseUInt64(const std::string& text, const char* name) {
    char* end = nullptr;
    errno = 0;
    const unsigned long long value = std::strtoull(text.c_str(), &end, 10);
    if (errno != 0 || end == text.c_str() || *end != '\0' || value == 0)
        throw std::invalid_argument(std::string("invalid ") + name);
    return static_cast<uint64_t>(value);
}

uint32_t ParseUInt32(const std::string& text, const char* name) {
    const uint64_t value = ParseUInt64(text, name);
    if (value > std::numeric_limits<uint32_t>::max())
        throw std::invalid_argument(std::string(name) + " is too large");
    return static_cast<uint32_t>(value);
}

double ParseDouble(const std::string& text, const char* name,
                   bool allow_zero) {
    char* end = nullptr;
    errno = 0;
    const double value = std::strtod(text.c_str(), &end);
    if (errno != 0 || end == text.c_str() || *end != '\0' ||
        !std::isfinite(value) || (allow_zero ? value < 0.0 : value <= 0.0))
        throw std::invalid_argument(std::string("invalid ") + name);
    return value;
}

double ParseFiniteDouble(const std::string& text, const char* name) {
    char* end = nullptr;
    errno = 0;
    const double value = std::strtod(text.c_str(), &end);
    if (errno != 0 || end == text.c_str() || *end != '\0' ||
        !std::isfinite(value))
        throw std::invalid_argument(std::string("invalid ") + name);
    return value;
}

void WriteBinaryPly(const std::filesystem::path& path,
                    const std::vector<double>& xyz,
                    const std::vector<double>& normals,
                    const std::vector<uint32_t>& face_ids) {
    const size_t count = face_ids.size();
    std::ofstream output(path, std::ios::binary);
    if (!output)
        throw std::runtime_error("could not create output PLY");
    output << "ply\n"
           << "format binary_little_endian 1.0\n"
           << "comment generated by cad_sampling.dll test\n"
           << "element vertex " << count << "\n"
           << "property float x\n"
           << "property float y\n"
           << "property float z\n"
           << "property float nx\n"
           << "property float ny\n"
           << "property float nz\n"
           << "property uint face_id\n"
           << "end_header\n";
    std::vector<PlyPoint> block;
    constexpr size_t block_size = 65536;
    block.reserve(std::min(count, block_size));
    for (size_t begin = 0; begin < count; begin += block_size) {
        const size_t end = std::min(count, begin + block_size);
        block.resize(end - begin);
        for (size_t i = begin; i < end; ++i) {
            block[i - begin] = {
                static_cast<float>(xyz[i * 3 + 0]),
                static_cast<float>(xyz[i * 3 + 1]),
                static_cast<float>(xyz[i * 3 + 2]),
                static_cast<float>(normals[i * 3 + 0]),
                static_cast<float>(normals[i * 3 + 1]),
                static_cast<float>(normals[i * 3 + 2]),
                face_ids[i]};
        }
        output.write(reinterpret_cast<const char*>(block.data()),
                     static_cast<std::streamsize>(
                         block.size() * sizeof(PlyPoint)));
        if (!output)
            throw std::runtime_error("failed while writing output PLY");
    }
}

void PrintUsage(const char* program) {
    std::cout
        << "Usage:\n  " << program
        << " input.stp output.ply [point_count] [voxel_size]"
           " [linear_deflection] [angular_deg] [relative_deflection]"
           " [parallel_meshing] [seed]"
           " [outer|all|visible]"
           " [perspective|orthographic x y z [max_incidence_deg]]"
           " [visibility_tolerance] [oversample_factor]\n\n"
        << "Defaults:\n"
        << "  point_count=100000, voxel_size=0 (disabled),\n"
        << "  linear_deflection=0.1, angular_deg=10, seed=1,\n"
        << "  surface_mode=outer, projection=orthographic,\n"
        << "  default view direction=(0,0,-1), max incidence=75 deg\n";
}

int Run(const std::vector<std::string>& args) {
    if (args.size() < 3 || args.size() > 19) {
        PrintUsage(args.empty() ? "cadsample_test" : args[0].c_str());
        return 2;
    }
    const std::filesystem::path input =
        std::filesystem::u8path(args[1]);
    const std::filesystem::path output =
        std::filesystem::u8path(args[2]);
    if (!std::filesystem::is_regular_file(input))
        throw std::invalid_argument("input STEP file does not exist");

    CadSampleOptions options{};
    cadsample_default_options(&options);
    if (args.size() > 3)
        options.target_point_count = ParseUInt64(args[3], "point_count");
    if (args.size() > 4)
        options.voxel_size = ParseDouble(args[4], "voxel_size", true);
    if (args.size() > 5)
        options.linear_deflection =
            ParseDouble(args[5], "linear_deflection", false);
    if (args.size() > 6)
        options.angular_deflection_deg =
            ParseDouble(args[6], "angular_deg", false);
    if (args.size() > 7)
        options.relative_deflection =
            args[7] == "0" ? 0u : ParseUInt32(args[7], "relative_deflection");
    if (args.size() > 8)
        options.parallel_meshing =
            args[8] == "0" ? 0u : ParseUInt32(args[8], "parallel_meshing");
    if (args.size() > 9)
        options.random_seed = ParseUInt32(args[9], "seed");
    if (args.size() > 10) {
        if (args[10] == "all")
            options.surface_mode = CADSAMPLE_SURFACE_ALL_FACES;
        else if (args[10] == "outer")
            options.surface_mode = CADSAMPLE_SURFACE_OUTER_SHELL;
        else if (args[10] == "visible")
            options.surface_mode = CADSAMPLE_SURFACE_VISIBLE;
        else
            throw std::invalid_argument(
                "surface mode must be outer, all, or visible");
    }
    size_t next = 11;
    if (args.size() > next &&
        (args[next] == "perspective" || args[next] == "orthographic")) {
        if (args[next] == "perspective") {
            options.projection_mode = CADSAMPLE_PROJECTION_PERSPECTIVE;
            options.camera_position[0] =
                ParseFiniteDouble(args[next + 1], "camera_x");
            options.camera_position[1] =
                ParseFiniteDouble(args[next + 2], "camera_y");
            options.camera_position[2] =
                ParseFiniteDouble(args[next + 3], "camera_z");
        } else if (args[next] == "orthographic") {
            options.projection_mode = CADSAMPLE_PROJECTION_ORTHOGRAPHIC;
            options.view_direction[0] =
                ParseFiniteDouble(args[next + 1], "view_x");
            options.view_direction[1] =
                ParseFiniteDouble(args[next + 2], "view_y");
            options.view_direction[2] =
                ParseFiniteDouble(args[next + 3], "view_z");
        } else {
            throw std::invalid_argument(
                "projection must be perspective or orthographic");
        }
        next += 4;
        if (args.size() > next) {
            options.max_incidence_angle_deg =
                ParseDouble(args[next], "max_incidence_deg", false);
            ++next;
        }
    }
    if (args.size() > next)
        options.visibility_tolerance = ParseDouble(args[next], "visibility_tolerance", true);
    if (args.size() > next + 1)
        options.visibility_oversample_factor = ParseUInt32(args[next + 1], "oversample_factor");

    CadSampleHandle handle = cadsample_create();
    if (!handle) throw std::runtime_error("could not create sampler handle");
    struct HandleGuard {
        CadSampleHandle value;
        ~HandleGuard() { cadsample_destroy(value); }
    } guard{handle};

    CadSampleResult result{};
    cadsample_init_result(&result);
    CadSampleStatus status =
        cadsample_load_step(handle, args[1].c_str(), &result);
    if (status != CADSAMPLE_STATUS_SUCCESS)
        throw std::runtime_error(
            std::string("STEP load failed: ") + result.error_message);
    const double load_ms = result.load_elapsed_ms;

    status = cadsample_generate(handle, &options, nullptr, &result);
    if (status != CADSAMPLE_STATUS_BUFFER_TOO_SMALL)
        throw std::runtime_error(
            std::string("sample query failed: ") + result.error_message);
    const double triangulation_ms = result.triangulation_elapsed_ms;
    const double generation_ms = result.generation_elapsed_ms;
    const double voxel_ms = result.voxel_elapsed_ms;
    const uint64_t capacity = result.required_point_capacity;
    if (capacity > std::numeric_limits<size_t>::max() / 3)
        throw std::runtime_error("sample result is too large");

    std::vector<double> xyz(static_cast<size_t>(capacity) * 3);
    std::vector<double> normals(static_cast<size_t>(capacity) * 3);
    std::vector<uint32_t> face_ids(static_cast<size_t>(capacity));
    CadSampleBuffers buffers{};
    cadsample_init_buffers(&buffers);
    buffers.capacity_points = capacity;
    buffers.xyz = xyz.data();
    buffers.normals = normals.data();
    buffers.face_ids = face_ids.data();
    status = cadsample_generate(handle, &options, &buffers, &result);
    if (status != CADSAMPLE_STATUS_SUCCESS)
        throw std::runtime_error(
            std::string("sampling failed: ") + result.error_message);

    double minimum[3]{
        std::numeric_limits<double>::infinity(),
        std::numeric_limits<double>::infinity(),
        std::numeric_limits<double>::infinity()
    };
    double maximum[3]{
        -std::numeric_limits<double>::infinity(),
        -std::numeric_limits<double>::infinity(),
        -std::numeric_limits<double>::infinity()
    };
    for (size_t i = 0; i < static_cast<size_t>(result.point_count); ++i) {
        for (size_t axis = 0; axis < 3; ++axis) {
            minimum[axis] = std::min(minimum[axis], xyz[i * 3 + axis]);
            maximum[axis] = std::max(maximum[axis], xyz[i * 3 + axis]);
        }
    }

    const auto ply_started = std::chrono::steady_clock::now();
    WriteBinaryPly(output, xyz, normals, face_ids);
    const double ply_write_ms = std::chrono::duration<double, std::milli>(
        std::chrono::steady_clock::now() - ply_started).count();
    const uintmax_t output_bytes = std::filesystem::file_size(output);
    std::cout << std::fixed << std::setprecision(3)
              << "Sampling succeeded\n"
              << "  input:       " << input.u8string() << "\n"
              << "  output:      " << output.u8string() << "\n"
              << "  requested:   " << options.target_point_count << "\n"
              << "  final:       " << result.point_count << "\n"
              << "  mode:        " << options.surface_mode << "\n"
              << "  projection:  " << options.projection_mode << "\n"
              << "  faces:       " << result.face_count << "\n"
              << "  triangles:   " << result.triangle_count << "\n"
              << "  area:        " << result.surface_area << "\n"
              << "  bounds min:  " << minimum[0] << ", " << minimum[1]
              << ", " << minimum[2] << "\n"
              << "  bounds max:  " << maximum[0] << ", " << maximum[1]
              << ", " << maximum[2] << "\n"
              << "  load:        " << load_ms << " ms\n"
              << "  triangulate: " << triangulation_ms << " ms\n"
              << "  generate:    " << generation_ms << " ms\n"
              << "  voxel:       " << voxel_ms << " ms\n"
              << "  buffer copy: " << result.sample_elapsed_ms << " ms\n"
              << "  PLY write:   " << ply_write_ms << " ms\n"
              << "  mesh cache:  " << result.mesh_cache_hit << "\n"
              << "  sample cache:" << result.sample_cache_hit << "\n"
              << "  PLY size:    " << output_bytes << " bytes\n";
    return 0;
}

#if defined(_WIN32)
std::string Utf8FromWide(const wchar_t* value) {
    const int size = WideCharToMultiByte(
        CP_UTF8, 0, value, -1, nullptr, 0, nullptr, nullptr);
    if (size <= 0) throw std::runtime_error("argument UTF-8 conversion failed");
    std::string result(static_cast<size_t>(size), '\0');
    WideCharToMultiByte(CP_UTF8, 0, value, -1, &result[0], size,
                        nullptr, nullptr);
    result.resize(static_cast<size_t>(size - 1));
    return result;
}
#endif

}  // namespace

#if defined(_WIN32)
int wmain(int argc, wchar_t** argv) {
    try {
        std::vector<std::string> args;
        args.reserve(static_cast<size_t>(argc));
        for (int i = 0; i < argc; ++i) args.push_back(Utf8FromWide(argv[i]));
        return Run(args);
    } catch (const std::exception& error) {
        std::cerr << "ERROR: " << error.what() << "\n";
        return 1;
    }
}
#else
int main(int argc, char** argv) {
    try {
        return Run(std::vector<std::string>(argv, argv + argc));
    } catch (const std::exception& error) {
        std::cerr << "ERROR: " << error.what() << "\n";
        return 1;
    }
}
#endif
